loginapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'loginapp'

urlpatterns = [
    path('', views.login, name='login'),
    path('landing/', views.landing, name='landing'),
    path('register/', views.register, name='register'),
    path('', views.gologout, name="logout"),
]

story9login/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('loginapp.urls')),
]

loginapp/models.py
from django.db import models

# Create your models here.

loginapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate, login as dj_login
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            dj_login(request,user)
            request.session["user"] = request.POST["username"]
            return redirect("/landing/")

    form = AuthenticationForm()
    return render(request, "login.html", {"form":form })

def register(request):
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            request.session["user"] = request.POST["username"]
            return redirect("")

    form = UserCreationForm()
    return render(request, "register.html", {"form":form })

@login_required(login_url="loginapp:login")
def landing(request):
    username = request.session.get("user")
    return render(request, "landing.html", {"username":username })

def gologout(request):
    if request.method == "POST":
        logout(request)
    return redirect("login.html")

loginapp/templates/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-iqcNtN3rj6Y1HX/R0a3zu3ngmbdwEa9qQGHdkXwSRoiE+Gj71p0UNDSm99LcXiXV" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    
    <title>Welcome</title>
</head>
<body>
    <h1>WELCOME BITCH</h1>
    <form action="{% url 'loginapp:logout' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Log Out!</button>
    </form>
</body>
</html>

loginapp/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-iqcNtN3rj6Y1HX/R0a3zu3ngmbdwEa9qQGHdkXwSRoiE+Gj71p0UNDSm99LcXiXV" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    <title>Document</title>
</head>
<body>
    <div class="card text-center">
        <div class="card-header">
            Featured
        </div>
        <div class="card-body">
            <form action="{% url 'loginapp:login' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit">Log In!</button>
            </form>
        </div>
        <div class="card-footer text-muted">
                <a id="hyper" href="/register/">Sign Up!</a>
        </div>
    </div>
</body>
</html>

loginapp/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-iqcNtN3rj6Y1HX/R0a3zu3ngmbdwEa9qQGHdkXwSRoiE+Gj71p0UNDSm99LcXiXV" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'register.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <title>Document</title>
</head>
<body>
    <div class="card text-center">
        <div class="card-header">
            Featured
        </div>
        <div class="card-body">
            <form action="{% url 'loginapp:register' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit">Sign Up!</button>
            </form>
        </div>
        <div class="card-footer text-muted">
            <a id="hyper" href="/">Sign In!</a>
        </div>
    </div>
</body>
</html>